In [ ]:
import numpy as np # Importing the numpy library and giving it the alias np

np.random.seed(94) # Setting the random seed for reproducibility
b = np.random.randint(45, 78, (7, 8)) # Generating a 7x8 array with random integers between 45 and 78
b # Displaying the generated array


array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[2] #2nd row

array([71, 56, 51, 58, 59, 47, 68, 77])

In [ ]:
b[:,7] #7th row


array([53, 60, 77, 55, 51, 47, 61])

In [ ]:
b[:,3]

array([67, 77, 58, 74, 69, 77, 69])

In [ ]:
b[1,3] #1st row and 3rd column position

77

In [ ]:
b[5,6]#5th row 6th column

67

In [ ]:
b[2,2]

51

In [ ]:
b[2,1:6]

array([56, 51, 58, 59, 47])

In [ ]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [ ]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[3:6,2:6]

array([[52, 74, 65, 53],
       [46, 69, 65, 75],
       [53, 77, 60, 67]])

In [ ]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [ ]:
b[1,1]

59

In [ ]:
b[1,4]

69

In [ ]:
b[1:6:2]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [ ]:
b[1:6:2,1:8:3]

array([[59, 69, 60],
       [45, 65, 55],
       [67, 60, 47]])